#!/bin/bash
# Generated by cc-statusline v1.4.0 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2026-03-11T07:02:24.316Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, tokens, burnrate, session
STATUSLINE_VERSION="1.4.0"

input=$(cat)

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- context window calculation (native) ----
context_pct=""
context_remaining_pct=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;37m'; fi; }  # default white

if [ "$HAS_JQ" -eq 1 ]; then
  used_pct=$(echo "$input" | jq -r '.context_window.used_percentage // empty' 2>/dev/null)
  if [ -n "$used_pct" ]; then
    context_used_pct=$(printf "%.0f" "$used_pct" 2>/dev/null || echo "$used_pct")
    context_remaining_pct=$(( 100 - context_used_pct ))
    (( context_remaining_pct < 0 )) && context_remaining_pct=0
    (( context_remaining_pct > 100 )) && context_remaining_pct=100

    if [ "$context_remaining_pct" -le 20 ]; then
      context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
    elif [ "$context_remaining_pct" -le 40 ]; then
      context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
    else
      context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
    fi

    context_pct="${context_remaining_pct}%"
  fi
fi

# ---- usage colors ----
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;189m'; fi; }  # lavender
cost_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # light gold
burn_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;220m'; fi; }   # bright gold
session_color() { 
  rem_pct=$(( 100 - session_pct ))
  if   (( rem_pct <= 10 )); then SCLR='38;5;210'  # light pink
  elif (( rem_pct <= 25 )); then SCLR='38;5;228'  # light yellow  
  else                          SCLR='38;5;194'; fi  # light green
  if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$SCLR"; fi
}

# ---- cost and usage extraction ----
session_txt=""; session_pct=0; session_bar=""
cost_usd=""; cost_per_hour=""; tpm=""; tot_tokens=""

# Extract cost and token data from Claude Code's native input
if [ "$HAS_JQ" -eq 1 ]; then
  # Cost data
  cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty' 2>/dev/null)
  total_duration_ms=$(echo "$input" | jq -r '.cost.total_duration_ms // empty' 2>/dev/null)

  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi

  # Token data from native context_window (no ccusage needed)
  input_tokens=$(echo "$input" | jq -r '.context_window.total_input_tokens // 0' 2>/dev/null)
  output_tokens=$(echo "$input" | jq -r '.context_window.total_output_tokens // 0' 2>/dev/null)

  if [ "$input_tokens" != "null" ] && [ "$output_tokens" != "null" ]; then
    tot_tokens=$(( input_tokens + output_tokens ))
    [ "$tot_tokens" -eq 0 ] && tot_tokens=""
  fi

  # Calculate tokens per minute from native data
  if [ -n "$tot_tokens" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to minutes and calculate rate
    tpm=$(echo "$tot_tokens $total_duration_ms" | awk '{if ($2 > 0) printf "%.0f", $1 * 60000 / $2; else print ""}')
  fi
else
  # Bash fallback for cost extraction
  cost_usd=$(echo "$input" | grep -o '"total_cost_usd"[[:space:]]*:[[:space:]]*[0-9.]*' | sed 's/.*:[[:space:]]*\([0-9.]*\).*/\1/')
  total_duration_ms=$(echo "$input" | grep -o '"total_duration_ms"[[:space:]]*:[[:space:]]*[0-9]*' | sed 's/.*:[[:space:]]*\([0-9]*\).*/\1/')

  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi

  # Token data from native context_window (bash fallback)
  input_tokens=$(echo "$input" | grep -o '"total_input_tokens"[[:space:]]*:[[:space:]]*[0-9]*' | sed 's/.*:[[:space:]]*\([0-9]*\).*/\1/')
  output_tokens=$(echo "$input" | grep -o '"total_output_tokens"[[:space:]]*:[[:space:]]*[0-9]*' | sed 's/.*:[[:space:]]*\([0-9]*\).*/\1/')

  if [ -n "$input_tokens" ] && [ -n "$output_tokens" ]; then
    tot_tokens=$(( input_tokens + output_tokens ))
    [ "$tot_tokens" -eq 0 ] && tot_tokens=""
  fi

  # Calculate tokens per minute from native data
  if [ -n "$tot_tokens" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    tpm=$(echo "$tot_tokens $total_duration_ms" | awk '{if ($2 > 0) printf "%.0f", $1 * 60000 / $2; else print ""}')
  fi
fi

# Session usage from Anthropic API (cached, non-blocking)
USAGE_CACHE="/tmp/claude-usage-cache.json"
USAGE_LOCK="/tmp/claude-usage-cache.lock"
USAGE_CACHE_MAX_AGE=120
USAGE_LOCK_MAX_AGE=300

usage_should_fetch=false
usage_now=$(date +%s)

if [ -f "$USAGE_CACHE" ]; then
  usage_cache_age=$(( usage_now - $(stat -f %m "$USAGE_CACHE" 2>/dev/null || echo 0) ))
  [ "$usage_cache_age" -ge "$USAGE_CACHE_MAX_AGE" ] && usage_should_fetch=true
elif [ -f "$USAGE_LOCK" ]; then
  usage_lock_age=$(( usage_now - $(stat -f %m "$USAGE_LOCK" 2>/dev/null || echo 0) ))
  [ "$usage_lock_age" -ge "$USAGE_LOCK_MAX_AGE" ] && usage_should_fetch=true
else
  usage_should_fetch=true
fi

if [ "$usage_should_fetch" = true ]; then
  # Create lock BEFORE fetch to prevent concurrent API calls
  touch "$USAGE_LOCK"
  (
    KEYCHAIN_SERVICE="Claude Code-credentials"
    OAUTH_CLIENT_ID="9d1c250a-e61b-44d9-88ed-5944d1962f5e"
    OAUTH_TOKEN_URL="https://console.anthropic.com/v1/oauth/token"

    # macOS keychain may HEX-encode JSON data; detect and decode
    read_keychain() {
      local raw
      raw=$(security find-generic-password -s "$1" -a "$(whoami)" -w 2>/dev/null) || return 1
      if echo "$raw" | jq -e '.' >/dev/null 2>&1; then
        echo "$raw"
      else
        echo "$raw" | xxd -r -p 2>/dev/null
      fi
    }

    write_keychain() {
      security delete-generic-password -s "$1" -a "$(whoami)" >/dev/null 2>&1
      security add-generic-password -s "$1" -a "$(whoami)" -w "$2" >/dev/null 2>&1
    }

    creds_json=$(read_keychain "$KEYCHAIN_SERVICE")
    token=$(echo "$creds_json" | jq -r '.claudeAiOauth.accessToken // empty' 2>/dev/null)

    fetch_usage() {
      curl -s --max-time 5 \
        -H "Authorization: Bearer $1" \
        -H "anthropic-beta: oauth-2025-04-20" \
        "https://api.anthropic.com/api/oauth/usage" 2>/dev/null
    }

    if [ -n "$token" ]; then
      resp=$(fetch_usage "$token")

      # If auth error, try refreshing the token
      if echo "$resp" | jq -e '.error.type == "authentication_error"' >/dev/null 2>&1; then
        refresh_token=$(echo "$creds_json" | jq -r '.claudeAiOauth.refreshToken // empty' 2>/dev/null)
        if [ -n "$refresh_token" ]; then
          refresh_resp=$(curl -s --max-time 5 \
            -X POST "$OAUTH_TOKEN_URL" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=refresh_token&refresh_token=${refresh_token}&client_id=${OAUTH_CLIENT_ID}" 2>/dev/null)

          new_access=$(echo "$refresh_resp" | jq -r '.access_token // empty' 2>/dev/null)
          new_refresh=$(echo "$refresh_resp" | jq -r '.refresh_token // empty' 2>/dev/null)
          expires_in=$(echo "$refresh_resp" | jq -r '.expires_in // empty' 2>/dev/null)

          if [ -n "$new_access" ] && [ -n "$new_refresh" ]; then
            # Update keychain with new tokens
            expires_at=$(( $(date +%s) * 1000 + ${expires_in:-28800} * 1000 ))
            updated_creds=$(echo "$creds_json" | jq \
              --arg at "$new_access" \
              --arg rt "$new_refresh" \
              --argjson ea "$expires_at" \
              '.claudeAiOauth.accessToken = $at | .claudeAiOauth.refreshToken = $rt | .claudeAiOauth.expiresAt = $ea')
            write_keychain "$KEYCHAIN_SERVICE" "$updated_creds"

            # Retry usage API with new token
            resp=$(fetch_usage "$new_access")
          fi
        fi
      fi

      if echo "$resp" | jq -e '.five_hour' >/dev/null 2>&1; then
        echo "$resp" > "$USAGE_CACHE"
        rm -f "$USAGE_LOCK"
      else
        touch "$USAGE_LOCK"
      fi
    else
      touch "$USAGE_LOCK"
    fi
  ) &
fi

weekly_txt=""
if [ -f "$USAGE_CACHE" ] && [ "$HAS_JQ" -eq 1 ]; then
  usage_data=$(cat "$USAGE_CACHE")
  five_util=$(echo "$usage_data" | jq -r '.five_hour.utilization // empty')
  five_reset=$(echo "$usage_data" | jq -r '.five_hour.resets_at // empty')
  seven_util=$(echo "$usage_data" | jq -r '.seven_day.utilization // empty')

  if [ -n "$five_util" ]; then
    session_pct=$(printf "%.0f" "$five_util" 2>/dev/null || echo "$five_util")
    session_bar=$(progress_bar "$session_pct" 10)

    reset_display=""
    if [ -n "$five_reset" ] && [ "$five_reset" != "null" ]; then
      reset_epoch=$(date -juf "%Y-%m-%dT%H:%M:%S" "${five_reset%%.*}" +%s 2>/dev/null)
      if [ -n "$reset_epoch" ]; then
        diff_sec=$((reset_epoch - usage_now))
        if [ "$diff_sec" -gt 0 ]; then
          rh=$((diff_sec / 3600)); rm=$(( (diff_sec % 3600) / 60 ))
          end_hm=$(fmt_time_hm "$reset_epoch")
          session_txt="$(printf '%dh %dm until reset at %s (%d%%)' "$rh" "$rm" "$end_hm" "$session_pct")"
        fi
      fi
    fi
    [ -z "$session_txt" ] && session_txt="${session_pct}% used"
  fi

  if [ -n "$seven_util" ]; then
    weekly_pct=$(printf "%.0f" "$seven_util" 2>/dev/null || echo "$seven_util")
    weekly_txt="7d:${weekly_pct}%"
  fi
fi

# Fallback when API data is unavailable
[ -z "$session_txt" ] && { session_txt="--"; session_bar=$(progress_bar 0 10); }
[ -z "$weekly_txt" ] && weekly_txt="7d:--"

# ---- render statusline ----
# Line 1: Core info (directory, git, model, claude code version, output style)
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  printf '  📟 %sv%s%s' "$(cc_version_color)" "$cc_version" "$(rst)"
fi
if [ -n "$output_style" ] && [ "$output_style" != "null" ]; then
  printf '  🎨 %s%s%s' "$(style_color)" "$output_style" "$(rst)"
fi

# Line 2: Context and session time
line2=""
if [ -n "$context_pct" ]; then
  context_bar=$(progress_bar "$context_remaining_pct" 10)
  line2="🧠 $(context_color)Context Remaining: ${context_pct} [${context_bar}]$(rst)"
fi
if [ -n "$session_txt" ]; then
  session_part="⌛ $(session_color)${session_txt}$(rst) $(session_color)[${session_bar}]$(rst)"
  if [ -n "$weekly_txt" ]; then
    session_part="$session_part  📅 $(session_color)${weekly_txt}$(rst)"
  fi
  if [ -n "$line2" ]; then
    line2="$line2  $session_part"
  else
    line2="$session_part"
  fi
fi
if [ -z "$line2" ] && [ -z "$context_pct" ]; then
  line2="🧠 $(context_color)Context Remaining: TBD$(rst)"
fi

# Line 3: Cost and usage analytics
line3=""
if [ -n "$cost_usd" ] && [[ "$cost_usd" =~ ^[0-9.]+$ ]]; then
  if [ -n "$cost_per_hour" ] && [[ "$cost_per_hour" =~ ^[0-9.]+$ ]]; then
    cost_per_hour_formatted=$(printf '%.2f' "$cost_per_hour")
    line3="💰 $(cost_color)\$$(printf '%.2f' "$cost_usd")$(rst) ($(burn_color)\$${cost_per_hour_formatted}/h$(rst))"
  else
    line3="💰 $(cost_color)\$$(printf '%.2f' "$cost_usd")$(rst)"
  fi
fi
if [ -n "$tot_tokens" ] && [[ "$tot_tokens" =~ ^[0-9]+$ ]]; then
  if [ -n "$tpm" ] && [[ "$tpm" =~ ^[0-9.]+$ ]]; then
    tpm_formatted=$(printf '%.0f' "$tpm")
    if [ -n "$line3" ]; then
      line3="$line3  📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
    else
      line3="📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
    fi
  else
    if [ -n "$line3" ]; then
      line3="$line3  📊 $(usage_color)${tot_tokens} tok$(rst)"
    else
      line3="📊 $(usage_color)${tot_tokens} tok$(rst)"
    fi
  fi
fi

# Print lines
if [ -n "$line2" ]; then
  printf '\n%s' "$line2"
fi
if [ -n "$line3" ]; then
  printf '\n%s' "$line3"
fi
printf '\n'
